export const MY_TICKETS_DETAILS_REQUEST = 'MY_TICKETS_DETAILS_REQUEST'
export const MY_TICKETS_DETAILS_SUCCESS = 'MY_TICKETS_DETAILS_SUCCESS'
export const MY_TICKETS_DETAILS_FAIL = 'MY_TICKETS_DETAILS_FAIL'

export const TICKETS_DETAILS_REQUEST = 'TICKETS_DETAILS_REQUEST'
export const TICKETS_DETAILS_SUCCESS = 'TICKETS_DETAILS_SUCCESS'
export const TICKETS_DETAILS_FAIL = 'TICKETS_DETAILS_FAIL'