export const MY_TICKETS_DETAILS_REQUEST = 'MY_TICKETS_DETAILS_REQUEST'
export const MY_TICKETS_DETAILS_SUCCESS = 'MY_TICKETS_DETAILS_SUCCESS'
export const MY_TICKETS_DETAILS_FAIL = 'MY_TICKETS_DETAILS_FAIL'

export const TICKETS_DETAILS_REQUEST = 'TICKETS_DETAILS_REQUEST'
export const TICKETS_DETAILS_SUCCESS = 'TICKETS_DETAILS_SUCCESS'
export const TICKETS_DETAILS_FAIL = 'TICKETS_DETAILS_FAIL'

export const TICKET_CREATE_REQUEST = 'TICKET_CREATE_REQUEST'
export const TICKET_CREATE_SUCCESS = 'TICKET_CREATE_SUCCESS'
export const TICKET_CREATE_FAIL = 'TICKET_CREATE_FAIL'
export const TICKET_CREATE_RESET = 'TICKET_CREATE_RESET'